pull_request_rules:
  - name: Automatic merge when approved by lhb008
    conditions:
      - "approved-reviews-by=lhb008"
      - base=master
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval
    conditions:
      - "approved-reviews-by>=baili-baili"
      - base=master
    actions:
      merge:
        method: merge
